name: sepaks
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  get: 4.6.5
  speech_to_text: ^5.4.2 
  flutter_tts: ^3.5.3
  avatar_glow: ^2.0.2
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true


